Update __init__.py
bug: 
+ the line `multiwalker_v0 = DepreciatedModule("multiwalker", "v0", "v2")` was duplicated on 2 lines. 
+ This causes an error when trying to import multiwalker_v1: `ImportError: cannot import name 'multiwalker_v1' from 'pettingzoo.sisl' (/home/ross/miniconda3/envs/pettingzoo_rllib/lib/python3.8/site-packages/pettingzoo/sisl/__init__.py)`

fix: I believe the intent was to make `multiwalker_v1` a `DepreciatedModule` like `multiwalker_v0`